### ISSUE TITLE
Question about G2O file

### ISSUE THREAD

**Issue by Quest2GM** [CogRob/distributed-mapper#10]
Hi @itzsid,

I have a quick question about the g2o file example in the README for intra-robot edges. The question has to do with how these three entries align:

`VERTEX_SE3:QUAT 6989586621679009792 0.324676 0.212487 0.042821 0.00270783 0.0121983 0.00760222 0.999893`
`VERTEX_SE3:QUAT 6989586621679009793 0.0716917 2.00724 -0.0729262 -0.00363348 0.00166876 0.00765756 0.999963`
`EDGE_SE3:QUAT 6989586621679009792 6989586621679009793 -0.390787 2.11308 0.0155589 0.00042254 -0.00328797 -0.010647 0.999938 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 1`

The `x` values for example for these two vertices are 0.324676 and 0.0716917. But the corresponding `dx` value in the edge that connects them is -0.390787. Should it not be -0.25298? When we are inputting our edges, do we need to deliberately add noise the `dx` value (which would explain the difference)?

Thanks for your reply,
Quest2GM

**Comment by itzsid** [comment]
Hi @Quest2GM, 

The edges in the synthetic dataset are simulated to be noisy to reflect the realistic conditions where odometry or communication measurements have errors. If you have perfect `dx` (without any noise), then you don't need to use this optimizer to find the most likely estimate. 

Thanks!

**Comment by Quest2GM** [comment]
Right, I understand that; maybe I should provide a little more context.

My robot provides odometry measurements in a ROS topic of type `nav_msgs/Odometry`. This topic provides the pose calculated through odometry, as well as the covariance matrix of the pose. These odometry measurements already have Gaussian noise added to them.

When adding a `VERTEX_SE3` to the g2o file, I just use the pose outputted in the above topic. When adding an `EDGE_SE3`, I simply calculate `dx` (and the other values `dy`, `dz`, etc.) by subtracting the previous pose from the current pose. In that sense, my `dx` value is exactly equal to the subtraction of the two corresponding VERTEX nodes.

Is this the way you would do it, or would you need to compute the VERTEX or EDGE in a different way?

Thanks again,
Quest2GM

**Comment by itzsid** [comment]
Correct. You can directly use the odometry measurements as `EDGE_SE3` since they are already noisy. `VERTEX_SE3` provides an initialization for the poses and you can initialize it using odometry too (similar to how you explained). This algorithm should be robust to bad initialization as well as long as you don't have outlier measurements.

Let me know if it's still not clear.

**Comment by Quest2GM** [comment]
Perfect thanks!
