### ISSUE TITLE
Question about ChordalFactor Jacobians

### ISSUE THREAD

**Issue by hjx-zju** [CogRob/distributed-mapper#11]
Hi,thank you for the great  work! @itzsid 
I have some problem deriding the jacobian of ChordalFactor in [line](https://github.com/CogRob/distributed-mapper/blob/a3bbfa9ea8e73fd09460f8ec008f3e8cc4940506/distributed_mapper_core/cpp/src/BetweenChordalFactor.h#L126). My jacobian wrt Ri is a bit different from the code,and my answer pattern is Ri*S*Rij.
```c++
  // fill in Jacobian wrt pose of key_i
  Matrix Mi = Matrix::Zero(12,6);
  Mi.block(0,0,3,3) = Ri_Rij*S1*Rijt;
  Mi.block(3,0,3,3) = Ri_Rij*S2*Rijt;
  Mi.block(6,0,3,3) = Ri_Rij*S3*Rijt;
``` 
The follows are my draft deriding the jacobian of pi and pj, the other jacobians match with the code.Could you please help me check out?
![备注 (12)](https://user-images.githubusercontent.com/67670531/225921334-f786ce81-5e78-4995-83a3-5c9abd021863.png)

**Comment by itzsid** [comment]
Hi @hjx-zju, Thanks for reaching out. Maybe check Section 3, in this paper: https://www.dropbox.com/s/x0n5r366u33fu7x/2015c-ICRA-initPGO3d.pdf?dl=0. It might help with derivation.

**Comment by hjx-zju** [comment]
Thank you for you reply!  I have found the mistake I made according to the paper. appreciate the help again！
