### ISSUE TITLE
Cannot Find GTSAM Checkout Point

### ISSUE THREAD

**Issue by MichaelJoker** [CogRob/distributed-mapper#2]
Hello, when I was trying to install the Prerequisites GTSAM, there was an error when running this command:
`git checkout b7c695fa71efd43b40972eec154df265617fc07d -b dist-mapper`
The error is:
`fatal: reference is not a tree: b7c695fa71efd43b40972eec154df265617fc07d`
How to fix this problem, thanks.

**Comment by itzsid** [comment]
@MichaelJoker Sorry but I'm not actively maintaining the repo. Can you try with a stable GTSAM branch and see if it works?

**Comment by MichaelJoker** [comment]
@itzsid Ok, thanks, the newest one can work for me, by just doing some modifications.

**Comment by itzsid** [comment]
@MichaelJoker Thanks! It will be great if you can create a PR for the modifications you made.

**Comment by treejustmoveon** [comment]
@MichaelJoker I have the same error.How did you solve it?

**Comment by itzsid** [comment]
@treejustmoveon, Can you try the instructions given in the docker file here: https://github.com/CogRob/distributed-mapper/blob/master/distributed_mapper_core/docker/distributed_mapper/Dockerfile

You can directly use an uploaded docker image as well, for example: 

```
docker pull awilby/distributed_mapper:latest
docker run awilby/distributed_mapper --nrRobots 4 --dataDir ../../data/example_4robots/
```
